.TH REMASTERSYS 1 "April 10, 2012" 
.SH NAME
remastersys-gtk \- official gui for remastersys
.SH SYNOPSIS
sudo remastersys-gtk 
.br
.br
 
.SH DESCRIPTION
Remastersys is a script used to make a bootable live cd or dvd from an
installed Ubuntu system or derivative. This is the gui.
.PP
This manual page documents
.BR remastersys .
.B remastersys
Makes a live cd or dvd iso file from and installed system

Makes system backup minus the user folders.
.SH AUTHOR
Tony Brijeski - Copyright (c) 2007,2008,2009,2010,2011,2012
.SH BUG REPORT
Report bugs to tb6517@yahoo.com
.SH URL
http://www.remastersys.com

